"use client";

import { Download } from "lucide-react";
import Button from "@/components/ui/Button";

type Props = {
  data: Record<string, unknown>;
  filename?: string;
};

export default function ExportReport({ data, filename = "guardian-report" }: Props) {
  function handleExport() {
    const mode = typeof data.mode === "string" ? data.mode : undefined;
    const MODE_NOTES: Record<string, string> = {
      offline:
        "All AI analysis was performed locally on-device via QVAC. No cloud AI was used. Wallet profile lookups (if any) use the public Solana RPC.",
      bare: "All AI analysis was performed locally on-device via QVAC. No cloud AI was used. Wallet profile lookups (if any) use the public Solana RPC.",
      llm: "Deterministic risk analysis was performed on-device. The plain-English explanation was generated by an external cloud AI API.",
      active:
        "Deterministic risk analysis was performed on-device. The plain-English explanation was generated by an external cloud AI API.",
      qvac: "All AI analysis was performed locally on-device via QVAC. No cloud AI was used. Wallet profile lookups (if any) use the public Solana RPC."
    };
    const note =
      (mode && MODE_NOTES[mode]) ??
      "Deterministic risk analysis was performed on-device. An AI model may have been used for the plain-English explanation.";
    const report = {
      exportedAt: new Date().toISOString(),
      tool: "Guardian Wallet Firewall",
      note,
      ...data
    };
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <Button variant="primary" className="w-full sm:w-auto" icon={Download} onClick={handleExport}>
      Export Report
    </Button>
  );
}
